name: Sonarr
version: 0.3.3
slug: sonarr
description: 新组用户和BitTorrent用户的智能PVR。
url: https://gh-proxy.com/github.com/hassio-addons/addon-sonarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:8989]
init: false
arch:
- aarch64
- amd64
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  8989/tcp: 8989
image: ghcr.nju.edu.cn/hassio-addons/sonarr/{arch}
