name: Bash Script Executer
version: 1.7.4
slug: bashscriptexecuter
description: 在这个Home assistant插件环境中执行自己的bash脚本。
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/bash_script_executer
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.nju.edu.cn/faserf/bash_script_executer-{arch}
map:
  - share:rw
init: false
panel_icon: mdi:web-box
options:
  script_path: "/share/scripts/mycoolscript.sh"
  script_path2: "false"
  script_path3: "false"
schema:
  script_path: str
  script_argument1: str?
  script_argument2: str?
  script_argument3: str?
  script_path2: str
  script2_argument1: str?
  script2_argument2: str?
  script2_argument3: str?
  script_path3: str
  script3_argument1: str?
  script3_argument2: str?
  script3_argument3: str?
