name: EMQX
version: 0.7.4
slug: emqx
description: 最可扩展的开源MQTT代理用于物联网。Mosquitto插件的替代品。
  the Mosquitto add-on
url: https://gh-proxy.com/github.com/hassio-addons/addon-emqx
codenotary: codenotary@frenck.dev
startup: services
ingress: true
ingress_port: 18083
ingress_stream: true
init: false
panel_icon: mdi:pipe
panel_title: EMQX
arch:
- aarch64
- amd64
map:
- ssl
- addon_config:rw
options:
  env_vars: []
host_network: true
schema:
  env_vars:
  - name: match(^EMQX_([A-Z0-9_])+$)
    value: str
image: ghcr.nju.edu.cn/hassio-addons/emqx/{arch}
