name: pterodactyl Panel Gameserver - BETA
version: 0.7.2
slug: pterodactyl_panel
description: 开源游戏服务器-目前尚未完全运行。
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/pterodactyl-panel
arch:
  - aarch64
  - amd64
image: ghcr.nju.edu.cn/faserf/pterodactyl-panel-{arch}
services:
  - mysql:need
#webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
map:
  - share:rw
  - ssl
ingress: true
init: false
panel_icon: mdi:controller
options:
  password:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  password: password
  ssl: bool
  certfile: str
  keyfile: str
  reset_database: bool?
ports:
  "443": 443
  80/tcp: 80
ports_description:
  80/tcp: Web interface http
  443/tcp: SSL Web interface
