name: PicoTTS
version: 1.6.1
slug: picotts
description: SVox的文本到语音合成器，包含在Android AOSP中。
url: https://gh-proxy.com/github.com/Poeschl-HomeAssistant-Addons/picotts
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
image: ghcr.nju.edu.cn/poeschl-homeassistant-addons/picotts-{arch}
init: false
ports:
  59126/tcp: 59126
ports_description:
  59126/tcp: Http interface of the REST wrapper
