name: JupyterLab
version: 0.15.10
slug: jupyterlablite
description: 创建包含活代码、方程式、可视化图和说明性文本的文档。
  explanatory text
url: https://gh-proxy.com/github.com/hassio-addons/addon-jupyterlab
codenotary: codenotary@frenck.dev
ingress: true
panel_icon: mdi:flask-outline
arch:
- aarch64
- amd64
homeassistant_api: true
init: false
map:
- config:rw
- share:rw
options:
  github_access_token: ''
  system_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  github_access_token: password
  system_packages:
  - str
  init_commands:
  - str
image: ghcr.nju.edu.cn/hassio-addons/jupyterlab/{arch}
