name: ympd
version: 1.5.1
slug: ympd
panel_icon: mdi:play-circle-outline
description: 一个简单的适用于任何MPD兼容音乐播放器的网络前端。
url: https://gh-proxy.com/github.com/Poeschl-HomeAssistant-Addons/ympd
ingress: true
ingress_port: 6680
arch:
- armv7
- armhf
- aarch64
- amd64
- i386
image: ghcr.nju.edu.cn/poeschl-homeassistant-addons/ympd-{arch}
init: false
ports:
  6680/tcp: null
ports_description:
  6680/tcp: Web Frontend (Not needed with ingress feature)
options:
  host: localhost
  port: '6600'
schema:
  host: str
  port: port
