name: Readarr
version: 0.3.1
slug: readarr
description: 书管理器与自动化（用于电子书的Sonarr）
url: https://gh-proxy.com/github.com/hassio-addons/addon-readarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:8787]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  8787/tcp: 8787
image: ghcr.nju.edu.cn/hassio-addons/readarr/{arch}
