name: Prowlarr
version: 0.18.0
slug: prowlarr
description: 索引管理器/代理基于流行的Arr栈构建，以集成您的各种PVR应用程序。
  your various PVR apps
url: https://gh-proxy.com/github.com/hassio-addons/addon-prowlarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:9696]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  9696/tcp: 9696
image: ghcr.nju.edu.cn/hassio-addons/prowlarr/{arch}
