---
version: 0.3.0
slug: vlc
name: VLC
description: "将您的设备转换为使用VLC播放媒体。"
url: https://gh-proxy.com/github.com/home-assistant/addons/tree/master/vlc
arch:
  - amd64
  - i386
  - armv7
  - aarch64
audio: true
discovery:
  - vlc_telnet
homeassistant: 2021.3.0.dev20210216
image: docker.m.daocloud.io/homeassistant/{arch}-addon-vlc
ingress: true
init: false
map:
  - share:ro
  - media:ro
options: {}
panel_icon: mdi:vlc
schema: false
stage: stable
startup: services
