name: SABnzbd
version: 0.3.3
slug: sabnzbd
description: 自由随意的二进制新闻阅读器
url: https://gh-proxy.com/github.com/hassio-addons/addon-sabnzbd/tree/main/README.md
codenotary: codenotary@frenck.dev
ingress: true
ingress_entry: sabnzbd/
panel_icon: mdi:arrow-down-bold
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  8080/tcp: null
image: ghcr.nju.edu.cn/hassio-addons/sabnzbd/{arch}
