name: Wiki.JS
version: 2.0.12
slug: wikijs
description: "最强大且可扩展的开源Wiki软件。"
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/wiki.js
arch:
  #- aarch64 (nodejs does support aarch64, but nodejs musl not?)
  - amd64
services:
  - mysql:need
startup: application
boot: auto
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
map:
  - ssl
ingress: true
init: false
panel_icon: mdi:wikipedia
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  log_level: info
schema:
  ssl: bool
  certfile: str
  keyfile: str
  log_level: list(error|warn|info|debug)?
  reset_database: bool?
ports:
  3000/tcp: 3000
  3443/tcp: 3443
ports_description: "最强大且可扩展的开源Wiki软件。"
  3000/tcp: HTTP Entrance port
  3443/tcp: HTTPS/SSL Entrance port
