name: yarr!
version: 0.3.1
slug: yarr
description: 又是一款RSS阅读器
url: https://gh-proxy.com/github.com/einschmidt/addon-yarr
panel_icon: mdi:rss-box
arch:
- armhf
- armv7
- amd64
- aarch64
ports:
  80/tcp: 7070
ports_description:
  80/tcp: Web interface
init: false
map:
- share:rw
- ssl
options:
  login:
    username: ''
    password: ''
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  login:
    username: str
    password: password
  ssl: bool
  certfile: str
  keyfile: str
  db_path: str?
image: ghcr.nju.edu.cn/einschmidt/yarr/{arch}
