name: Log Viewer
version: 0.17.1
slug: logviewer
description: 基于浏览器的日志实用工具，用于家庭助手（Home Assistant）。
url: https://gh-proxy.com/github.com/hassio-addons/addon-log-viewer
codenotary: codenotary@frenck.dev
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:text-box-outline
homeassistant: 0.92.0b2
arch:
- aarch64
- amd64
- armv7
homeassistant_api: true
auth_api: true
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
map:
- homeassistant_config
- share
- ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  leave_front_door_open: bool?
image: ghcr.nju.edu.cn/hassio-addons/log-viewer/{arch}
