name: The Lounge
version: 0.20.0
slug: thelounge
description: "一个自托管的网络IRC客户端"
url: https://gh-proxy.com/github.com/hassio-addons/addon-thelounge
codenotary: codenotary@frenck.dev
arch:
- aarch64
- amd64
- armv7
ingress: true
ingress_stream: true
panel_admin: false
init: false
panel_icon: mdi:chat
ports:
  80/tcp: null
ports_description: "一个自托管的网络IRC客户端"
  80/tcp: The Lounge Web UI (Not required for Ingress)
map:
- ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  default_theme: default
  themes:
  - thelounge-theme-solarized
  users: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  default_theme: str
  themes:
  - str
  users:
  - str
image: ghcr.nju.edu.cn/hassio-addons/thelounge/{arch}
