name: Home Assistant Git Exporter
version: 1.17.1
slug: git-exporter
description: "将您的Home Assistant配置导出到Git存储库中。"
  your choice
url: https://gh-proxy.com/github.com/Poeschl-HomeAssistant-Addons/git-exporter
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: once
boot: manual
init: false
image: ghcr.nju.edu.cn/poeschl-homeassistant-addons/git-exporter-{arch}
hassio_api: true
hassio_role: manager
map:
- config
options:
  repository:
    url: ''
    username: ''
    password: ''
    pull_before_push: true
    commit_message: Home Assistant Git Exporter
    branch_name: main
  export:
    lovelace: true
    addons: true
    esphome: true
    node_red: true
  check:
    enabled: true
    check_for_secrets: true
    check_for_ips: true
  exclude:
  - '*.db'
  - '*.log*'
  - __pycache__
  - ._*
  - .DS_Store
  - deps/
  - known_devices.yaml
  - tts/
  - '*.db-shm'
  - '*.db-wal'
  - '*.gz'
  secrets: []
  allowed_secrets: []
  dry_run: false
schema:
  repository:
    url: match(https://.*)
    email: match(.+@.+)?
    username: str
    password: password
    pull_before_push: bool
    commit_message: str
    branch_name: str
    ssl_verification: bool?
  export:
    lovelace: bool
    addons: bool
    esphome: bool
    node_red: bool
  check:
    enabled: bool
    check_for_secrets: bool
    check_for_ips: bool
  exclude:
  - str
  secrets:
  - str
  allowed_secrets:
  - str
  dry_run: bool
