name: phpMyAdmin
version: 0.1.1
slug: phpmyadmin
description: 一个用于官方MariaDB插件的网页界面。
url: https://gh-proxy.com/github.com/hassio-addons/addon-phpmyadmin
codenotary: codenotary@frenck.dev
ingress: true
ingress_stream: true
panel_icon: mdi:database
arch:
- aarch64
- amd64
- armv7
init: false
services:
- mysql:need
hassio_api: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  upload_limit: int?
image: ghcr.nju.edu.cn/erik73/phpmyadmin/{arch}
