---
version: 1.10.0
slug: openwakeword
name: openWakeWord
description: "使用怀俄明协议打开唤醒词"
url: https://gh-proxy.com/github.com/home-assistant/addons/blob/master/openwakeword
arch:
  - amd64
  - aarch64
  - armv7
init: false
discovery:
  - wyoming
backup_exclude:
  - "*.tflite"
map:
  - share:ro
options:
  threshold: 0.5
  trigger_level: 1
  debug_logging: false
schema:
  threshold: float
  trigger_level: int
  debug_logging: bool
ports:
  "10400/tcp": null
homeassistant: 2023.9.0.dev20230809
image: docker.m.daocloud.io/homeassistant/{arch}-addon-openwakeword
