name: Gutenprint Printer
version: 5.3.4-11-edge
slug: gutenprint-printer
description: 支持使用Gutenprint打印驱动程序的打印机。
url: https://gh-proxy.com/github.com/Eskander/ha-addon-printer
arch:
  - amd64
  - aarch64
  - armv7
stage: experimental
init: false
environment:
  PORT: "631"
webui: http://[HOST]:[PORT:631]
host_network: true
usb: true
map:
  - type: data
    path: /etc/cups/
    read_only: false
  - type: addon_config
    path: /var/lib/gutenprint-printer-app
    read_only: false
image: ghcr.nju.edu.cn/openprinting/gutenprint-printer-app
