name: chrony
version: 5.1.0
slug: chrony
description: 一个本地NTP（网络时间协议）服务器，用于摄像头等设备。
url: https://gh-proxy.com/github.com/hassio-addons/addon-chrony
codenotary: codenotary@frenck.dev
startup: system
arch:
- aarch64
- amd64
- armv7
hassio_api: true
init: false
privileged:
- SYS_TIME
ports:
  123/udp: 123
ports_description:
  123/udp: NTP; Network Time Protocol
options:
  set_system_clock: true
  mode: pool
  ntp_pool: pool.ntp.org
  ntp_server:
  - 54.39.13.155
  - briareus.schulte.org
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  set_system_clock: bool
  ntp_pool: str?
  ntp_server:
  - str?
  mode: list(pool|server)
image: ghcr.nju.edu.cn/hassio-addons/chrony/{arch}
