---
version: 1.0.0
slug: microwakeword
name: microwakeword
description: 使用怀俄明协议的微唤醒词（microWakeWord）
url: https://gh-proxy.com/github.com/rhasspy/hassio-addons/tree/master/microwakeword
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
options:
  debug_logging: false
schema:
  debug_logging: bool
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
