{
  "version": "0.0.4",
  "slug": "k2fsa",
  "codenotary": "djhhui@gmail.com",
  "name": "k2fsa",
  "description": "offline Speech-to-text service for Home Assistant",
  "arch": [
    "amd64"
  ],
  "init": false,
  "ingress": true,
  "ports": {
    "6006/tcp": 6006,
    "10300/tcp": 10300
  },
  "map": [
    "config:rw"
  ],
  "backup_exclude": [
    "/config/addons_config/k2fsa"
  ]
}
