name: Bazarr
version: 0.4.1
slug: bazarr
description: 下载并管理Sonarr和Radarr的字幕
url: https://gh-proxy.com/github.com/hassio-addons/addon-bazarr/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:6767]
init: false
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
- share:rw
- media:rw
ports:
  6767/tcp: 6767
image: ghcr.nju.edu.cn/hassio-addons/bazarr/{arch}
