name: Switch LAN Play Server
version: 1.6.2
slug: switch-lan-play-server
description: 任天堂Switch局域网游戏 - 服务器
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/switch_lan_play_server
arch:
  - armhf
  - armv7
  - amd64
  - i386
#image: ghcr.nju.edu.cn/faserf/switch_lan_play_server-{arch}
panel_icon: mdi:local-area-network
init: false
schema:
  username: str?
  password: str?
ports:
  "11451": 11451
ports_description:
  11451/tcp: SLP Server Port
